//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notch.Data.EntityFramework.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotchContext : DbContext
    {
        public NotchContext()
            : base("name=NotchConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProducerEFEntity> ProducerEFEntity { get; set; }
        public virtual DbSet<TrackEFEntitys> TrackEFEntitys { get; set; }
        public virtual DbSet<TrackEFEntity> TrackEFEntity { get; set; }
    }
}
