//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notch.Data.EntityFramework.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProducerTrack
    {
        public int Id { get; set; }
        public int ProducerId { get; set; }
        public int TrackId { get; set; }
    
        public virtual Producer Producer { get; set; }
        public virtual Track Track { get; set; }
    }
}
