//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notch.Data.EntityFramework.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackEFEntitys
    {
        public int Id { get; set; }
        public int ProducerEFEntityId { get; set; }
        public int TrackEFEntityId { get; set; }
    
        public virtual ProducerEFEntity ProducerEFEntity { get; set; }
        public virtual TrackEFEntity TrackEFEntity { get; set; }
    }
}
