//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notch.Data.EntityFramework.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackEFEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrackEFEntity()
        {
            this.TrackEFEntitys = new HashSet<TrackEFEntitys>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Length { get; set; }
        public byte BPM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackEFEntitys> TrackEFEntitys { get; set; }
    }
}
